export enum ReservationStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  UNPAID = 'UNPAID',
  REFUNDED = 'REFUNDED',
  CANCELED = 'CANCELED',
  CART = 'CART',
}
